In [1]:
import numpy as np

In [2]:
escalar = 5.679
vector = np.array([3,4,5])
matriz = np.array([[1,2],[3,4],[5,6]])

In [3]:
print(vector.shape)
print(matriz.shape)
A = vector + matriz  # IMPORTANTE, NO SE PUEDEN SUMAR POR SUS DIMENSIONES

(3,)
(3, 2)


ValueError: operands could not be broadcast together with shapes (3,) (3,2) 

In [4]:
A = matriz.T + vector

In [12]:
print('Vector: ', vector) 
print('Matriz:', matriz.T[0], matriz.T[1])
print(A)

Vector:  [3 4 5]
Matriz: [1 3 5] [2 4 6]
[[ 4  7 10]
 [ 5  8 11]]


In [13]:
C = matriz + 42   # Suma con escalar

In [14]:
print(C)

[[43 44]
 [45 46]
 [47 48]]


In [16]:
D = matriz + np.array([[42],[42],[42]])  #Suma con matriz de 1x3
print(D)

[[43 44]
 [45 46]
 [47 48]]
