In [30]:
import numpy as np
import pandas as pd

In [5]:
np.array([10, 20, 24, 5, 15, 50]) #Creacion de arreglos

array([10, 20, 24,  5, 15, 50])

In [6]:
a = np.array([10, 30, 20, 4, 30, 51, 7, 2, 4, 40, 100])
a[4]

30

### Impresiones

In [8]:
a[3:]

array([30, 51, 40])

In [10]:
a[3:7]

array([ 4, 30, 51,  7])

In [9]:
a[1::4]

array([30, 51, 40])

In [ ]:
### Arreglos

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
ones = np.ones((4,5))
ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
type(ones)

numpy.ndarray

In [17]:
type(ones[3])

numpy.ndarray

In [25]:
np.arange(25) #Limite superior excluyente

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [26]:
np.arange(5,30) #Limite superior excluyente

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29])

In [27]:
np.arange(5, 50, 5) #Limite superior excluyente

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [28]:
np.full( ( 3, 5 ), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [29]:
np.diag ( [0, 3, 9, 10] )

array([[ 0,  0,  0,  0],
       [ 0,  3,  0,  0],
       [ 0,  0,  9,  0],
       [ 0,  0,  0, 10]])

In [19]:
# np.linspace(MINIMO,MAXIMO,NUMERO DE ELEMENTOS)
np.linspace(3,10,5)

array([ 3.  ,  4.75,  6.5 ,  8.25, 10.  ])

In [21]:
b = np.array( [['x', 'y', 'z'], ['a', 'c', 'e']])
print(b)
type(b)

[['x' 'y' 'z']
 ['a' 'c' 'e']]


numpy.ndarray

In [22]:
b.ndim #para ver la cantidad de dimensiones

2

### Comandos

In [23]:
c = [12, 4, 10, 40, 2]
np.sort(c)

array([ 2,  4, 10, 12, 40])

In [24]:
cabeceras = [ ('nombre', 'S10' ), ('edad', int) ] #Estructura de un array detallado
datos = [ ('Juan', 10), ('Maria', 70), ('Javier', 42), ('Samuel', 15) ]
usuarios = np.array(datos, dtype = cabeceras)

np.sort(usuarios, order = 'edad' ) #parametro de orden

array([(b'Juan', 10), (b'Samuel', 15), (b'Javier', 42), (b'Maria', 70)],
      dtype=[('nombre', 'S10'), ('edad', '<i4')])

### Numpy Challenge

In [31]:
headers = [('nombre', 'S100'), ('edad', int), ('profesion', 'S100')]
data = [
  ('Jose', 18, 'Estudiante'),
  ('Rafel', 35, 'Profesor'),
  ('Juan', 27, 'Mecanico'),
  ('Ana', 23, 'Oficial de policia'),
  ('Gabriela', 29, 'Ingeniero'),
]

peoples = np.array(data, dtype=headers)
peoples = np.sort(peoples, order='nombre')
df = pd.DataFrame(peoples)
df

nombre  edad              profesion
0       b'Ana'    23  b'Oficial de policia'
1  b'Gabriela'    29           b'Ingeniero'
2      b'Jose'    18          b'Estudiante'
3      b'Juan'    27            b'Mecanico'
4     b'Rafel'    35            b'Profesor'