In [17]:
import torch
import numpy as np
import pandas as pd

## Trabajando con tensores

In [2]:
torch.__version__

'1.6.0'

In [3]:
# Construccion de un tensor de 1
tensor_a = torch.ones(2, 2)
tensor_a

tensor([[1., 1.],
        [1., 1.]])

In [4]:
# Tensor con valores aleatoreos con un bajo limite de decimales 
tensor_b = torch.Tensor(2,2)
print(tensor_b)
tensor_b.uniform_(0,1)  # Aletoreos entre 0 y 1 con 4 decimales

tensor([[ 0.0000, 18.9802],
        [ 0.0000,  0.0000]])


tensor([[0.0149, 0.3631],
        [0.3151, 0.2437]])

In [5]:
# Aletoreos entre 0 y 1 con 4 decimales usando RAND
tensor_c = torch.rand(2,2)
tensor_c

tensor([[0.6093, 0.7396],
        [0.1816, 0.8911]])

In [6]:
print(tensor_c.shape)  #Comando para ver las dimensiones que tiene el tensor
reshaped = tensor_c.view(4,1)
reshaped

torch.Size([2, 2])


tensor([[0.6093],
        [0.7396],
        [0.1816],
        [0.8911]])

In [7]:
points = torch.tensor([[1, 2], [3, 4]])   # puedo usar t minúscula ya que no quiero aleatorio.
print(points)
points[0][1]
print(points)
points[0][1] = 6.5
print(points)
points.storage()

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])
tensor([[1, 6],
        [3, 4]])


 1
 6
 3
 4
[torch.LongStorage of size 4]

In [8]:
points, points.stride()

(tensor([[1, 6],
         [3, 4]]),
 (2, 1))

In [9]:
p_t =points.t() #para la traspuesta
p_t, p_t.stride()

(tensor([[1, 3],
         [6, 4]]),
 (1, 2))

In [10]:
tensor_x = torch.tensor([1, 2, 3, 4])
print(tensor_x)
torch.unsqueeze(tensor_x, 0)
torch.unsqueeze(tensor_x, 1)

tensor([1, 2, 3, 4])


tensor([[1],
        [2],
        [3],
        [4]])

In [11]:
numpyArray = np.random.randn(2, 2)
torch.from_numpy(numpyArray)

tensor([[ 0.5130, -2.6239],
        [-0.6426,  0.3833]], dtype=torch.float64)

## Representando datos con tensores

In [13]:
from_numpy = torch.from_numpy(numpyArray)
print(from_numpy)
print(torch.mean(from_numpy))
print(torch.mean(from_numpy, dim=0)) # Promedio de filas
print(torch.mean(from_numpy, dim=1)) # Promedio de columnas

tensor([[ 0.5130, -2.6239],
        [-0.6426,  0.3833]], dtype=torch.float64)
tensor(-0.5925, dtype=torch.float64)
tensor([-0.0648, -1.1203], dtype=torch.float64)
tensor([-1.0554, -0.1296], dtype=torch.float64)


In [14]:
torch.std(from_numpy, dim=1) # Desviacion estandar de las columnas por separado

tensor([2.2181, 0.7254], dtype=torch.float64)

In [15]:
torch.save(from_numpy, 'tensor.t') # Formas de guardar un archivo

In [16]:
load = torch.load('tensor.t')
load

tensor([[ 0.5130, -2.6239],
        [-0.6426,  0.3833]], dtype=torch.float64)

In [18]:
url = "https://raw.githubusercontent.com/amanthedorkknight/fifa18-all-player-statistics/master/2019/data.csv"
dataframe = pd.read_csv(url)
dataframe.head(5)

Unnamed: 0      ID               Name  Age  \
0           0  158023           L. Messi   31   
1           1   20801  Cristiano Ronaldo   33   
2           2  190871          Neymar Jr   26   
3           3  193080             De Gea   27   
4           4  192985       K. De Bruyne   27   

                                            Photo Nationality  \
0  https://cdn.sofifa.org/players/4/19/158023.png   Argentina   
1   https://cdn.sofifa.org/players/4/19/20801.png    Portugal   
2  https://cdn.sofifa.org/players/4/19/190871.png      Brazil   
3  https://cdn.sofifa.org/players/4/19/193080.png       Spain   
4  https://cdn.sofifa.org/players/4/19/192985.png     Belgium   

                                  Flag  Overall  Potential  \
0  https://cdn.sofifa.org/flags/52.png       94         94   
1  https://cdn.sofifa.org/flags/38.png       94         94   
2  https://cdn.sofifa.org/flags/54.png       92         93   
3  https://cdn.sofifa.org/flags/45.png       91         93   
4   https://cdn.sofifa.org/flags/7.png       91         92   

                  Club  ... Composure Marking StandingTackle  SlidingTackle  \
0         FC Barcelona  ...      96.0    33.0           28.0           26.0   
1             Juventus  ...      95.0    28.0           31.0           23.0   
2  Paris Saint-Germain  ...      94.0    27.0           24.0           33.0   
3    Manchester United  ...      68.0    15.0           21.0           13.0   
4      Manchester City  ...      88.0    68.0           58.0           51.0   

  GKDiving  GKHandling  GKKicking  GKPositioning GKReflexes Release Clause  
0      6.0        11.0       15.0           14.0        8.0        €226.5M  
1      7.0        11.0       15.0           14.0       11.0        €127.1M  
2      9.0         9.0       15.0           15.0       11.0        €228.1M  
3     90.0        85.0       87.0           88.0       94.0        €138.6M  
4     15.0        13.0        5.0           10.0       13.0        €196.4M  

[5 rows x 89 columns]

In [19]:
dataframe.columns

Index(['Unnamed: 0', 'ID', 'Name', 'Age', 'Photo', 'Nationality', 'Flag',
       'Overall', 'Potential', 'Club', 'Club Logo', 'Value', 'Wage', 'Special',
       'Preferred Foot', 'International Reputation', 'Weak Foot',
       'Skill Moves', 'Work Rate', 'Body Type', 'Real Face', 'Position',
       'Jersey Number', 'Joined', 'Loaned From', 'Contract Valid Until',
       'Height', 'Weight', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW',
       'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM',
       'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB', 'Crossing',
       'Finishing', 'HeadingAccuracy', 'ShortPassing', 'Volleys', 'Dribbling',
       'Curve', 'FKAccuracy', 'LongPassing', 'BallControl', 'Acceleration',
       'SprintSpeed', 'Agility', 'Reactions', 'Balance', 'ShotPower',
       'Jumping', 'Stamina', 'Strength', 'LongShots', 'Aggression',
       'Interceptions', 'Positioning', 'Vision', 'Penalties', 'Composure',
       'Marking', 'StandingTackle', 'SlidingT

In [20]:
# Creacion de un sub-set de 18159 x 5
subset = dataframe[['Overall','Age','International Reputation', 'Weak Foot',
       'Skill Moves' ]].dropna(axis=0, how='any')

columns = subset.columns[1:]
players = torch.tensor(subset.values).float()
players.shape, players.type()

(torch.Size([18159, 5]), 'torch.FloatTensor')

In [21]:
data = players[:, 1:]
data, data.shape

(tensor([[31.,  5.,  4.,  4.],
         [33.,  5.,  4.,  5.],
         [26.,  5.,  5.,  5.],
         ...,
         [16.,  1.,  3.,  2.],
         [17.,  1.,  3.,  2.],
         [16.,  1.,  3.,  2.]]),
 torch.Size([18159, 4]))

In [22]:
target = players[:, 0]
target, target.shape

(tensor([94., 94., 92.,  ..., 47., 47., 46.]), torch.Size([18159]))

In [23]:
mean = torch.mean(data, dim=0)
mean

tensor([25.1225,  1.1132,  2.9473,  2.3613])

In [24]:
std = torch.std(data, dim=0)
std

tensor([4.6706, 0.3940, 0.6605, 0.7562])

In [25]:
norm = (data - mean)/torch.sqrt(std)
norm

tensor([[ 2.7196,  6.1919,  1.2953,  1.8845],
        [ 3.6450,  6.1919,  1.2953,  3.0345],
        [ 0.4060,  6.1919,  2.5258,  3.0345],
        ...,
        [-4.2211, -0.1804,  0.0648, -0.4155],
        [-3.7584, -0.1804,  0.0648, -0.4155],
        [-4.2211, -0.1804,  0.0648, -0.4155]])

In [26]:
# Obtencion de tablas con criterios,
    # GE = [G]reater or [E]qual
    # GT = [G]o [T]o
    # LE = [L]ower or [E]qual

good = data[torch.ge(target, 85)]
average = data[torch.gt(target, 70) & torch.lt(target, 85)]
notSoGood = data[torch.le(target, 70)]

goodMean = torch.mean(good, dim=0)
averageMean = torch.mean(average, dim=0)
notSoGoodMean = torch.mean(notSoGood, dim=0)

# goodMean, averageMean, notSoGoodMean

# Zip para agrupar todos los argumentos e iterar
for i, args in enumerate(zip(columns, goodMean, averageMean, notSoGoodMean)):
  print('{:25} {:6.2f} {:6.2f} {:6.2f}'.format(*args))

Age                        28.35  27.23  24.37
International Reputation    3.38   1.36   1.01
Weak Foot                   3.45   3.11   2.89
Skill Moves                 3.04   2.75   2.22
